#!/bin/sh

wait_for_zen_to_start_samba() {
  while ! [ "`docker inspect --format='{{json .State.Running }}' zen 2>>/dev/null`" == "true" ]
  do
    sleep 1
  done
  docker pull niccokunzmann/samba-share 1>>/dev/null
  docker run -e RUN_ARGUMENTS="--net=host" niccokunzmann/samba-share zen | sh 1>>/dev/null
}

start_zen_bash() {
  location="`pwd`"
  cd /data/docker-compose
  if docker inspect zen 1>>/dev/null 2>>/dev/null
  then
    # There is a zen container but there shall be none.
    # We commit the content of zen to start a new one based on the old zen.
    message="Committing container named \"zen\"."
    echo "$message"
    new_image=`docker commit --pause=true --message="$message" zen`
    docker tag -f $new_image coderdojo/zen 1>>/dev/null
    docker-compose stop zen 1>>/dev/null
    docker-compose rm zen 1>>/dev/null
    docker rm zen 1>>/dev/null
  fi
  wait_for_zen_to_start_samba &
  # publish ports
  #   https://docs.docker.com/engine/userguide/networking/default_network/binding/  
  echo "IPs: "`ip -o addr | grep -o -E 'inet6?\s+[0123456789abcdef.:]+' | grep -o -E '\S+$'`
  docker-compose run --service-ports --name zen zen "$@"
  cd "$location"
  echo "Run \"start_zen_bash\" to enter the zen command line."
}

start_zen_bash "$@"

